lattice_publisher:
  ros__parameters:
    surface: "cylindrical" # "planar" or "cylindrical" or "spherical"
    towards: "axisZ" # "origin" or "axisZ" or "fixed"
    order: "horizontal" # "horizontal" or "vertical"
    frame_id: 'plant' # lattice points with respect to which frame e.g. 'panda_link0'
    x_lb_ub: [0.2, 0.3] #meter
    y_lb_ub: [-0.15, 0.1] #meter
    z_lb_ub: [-0.3, 0.3] #meter
    theta_hor_lb_ub: [-30.0, 30.0] #degrees (for spherical and cylindrical)
    theta_ver_lb_ub: [-10.0, 10.0] #degrees (for spherical)
    x_stepSize: 0.05 #meter
    y_stepSize: 0.05 #meter
    z_stepSize: 0.05 #meter
    theta_hor_stepSize: 10.0 #degrees
    theta_ver_stepSize: 5.0 #degrees
    rate: 5 # Hz
    fixed_orientation: [0.0, -1.5708, -1.3] # [roll, pitch, yaw] in radian